name: Resume S3 bucket

on: 
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: "/Users/muskan/Downloads/resume-challenge"
          destination_dir: "s3://cloudresume-yash/AWS-portfolio/"
          acl: "public-read"

